server:
    port: 8088


rocketmq:
    endpoint: 0.0.0.0:8081
    producer-config:
        topic: TopicTest
    consumer-config:
        group: YourConsumerGroup
        topic: TopicTest
        tag: "*"
        consumptionThreadCount: 20



    name-server: 0.0.0.0:9876
    producer:
        group: interview-group
