server:
    port: 8088


rocketmq:
    endpoint: 0.0.0.0:8081
    producer-config:
        topic: TestTopic
    consumer-config:
        group: YourConsumerGroup
        topic: TestTopic
        tag: "*"
        consumptionThreadCount: 20



